// <auto-generated />
namespace TOPOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dds));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191546497_dds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
